# Authentication
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"

# Users
USER_NOT_FOUND = "USER_NOT_FOUND"
EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
PASSWORD_NOT_VALID = "PASSWORD_NOT_VALID"

# Jobs
JOB_NOT_FOUND = "JOB_NOT_FOUND"

# Receipts
RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND"
RECEIPT_PARSE_FAILED = "RECEIPT_PARSE_FAILED"

# Request errors
VALIDATION_ERROR = "VALIDATION_ERROR"

# Generic
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
FORBIDDEN = "FORBIDDEN"
UNAUTHORIZED = "UNAUTHORIZED"