# Authentication
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"

# Users
USER_NOT_FOUND = "USER_NOT_FOUND"
EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
PASSWORD_INVALID = "PASSWORD_INVALID"

# Devices
DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
DEVICE_INVALID = "DEVICE_INVALID"
DEVICE_INVALID_NAME = "DEVICE_INVALID_NAME"
DEVICE_INVALID_MAC = "DEVICE_INVALID_MAC"
DEVICE_INVALID_IP = "DEVICE_INVALID_IP"
DEVICE_ALREADY_REGISTERED = "DEVICE_ALREADY_REGISTERED"
 
# Jobs
JOB_NOT_FOUND = "JOB_NOT_FOUND"
JOB_INVALID = "JOB_INVALID"
JOB_INVALID_ID = "JOB_INVALID_ID"
JOB_ALREADY_EXISTS = "JOB_ALREADY_EXISTS"

# Receipts
RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND"
RECEIPT_PARSE_FAILED = "RECEIPT_PARSE_FAILED"
DEVICE_REQUIRED = "DEVICE_REQUIRED"

# Request errors
VALIDATION_ERROR = "VALIDATION_ERROR"

# Generic
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
FORBIDDEN = "FORBIDDEN"
UNAUTHORIZED = "UNAUTHORIZED"